[install]
is_configured = 1
state = enabled

[ui]
is_visible = 0
label = Default indexes

[launcher]
author = szilard
description = Configure new indexes and modify default indexes
version = 1.0.0

[package]
id = szilard_default_indexes
