# Global settings for all indexes
[default]
frozenTimePeriodInSecs = 86400
maxTotalDataSizeMB = 1024

[linux]
homePath   = $SPLUNK_DB/linux/db
coldPath   = $SPLUNK_DB/linux/colddb
thawedPath = $SPLUNK_DB/linux/thaweddb