[indexer_discovery:indexer_discovery]
pass4SymmKey = admin123
manager_uri = https://splunk.cm.gyoriszilard.hu:8089

[tcpout:idx_group]
indexerDiscovery = indexer_discovery
autoLBFrequency = 30
forceTimebasedAutoLB = true
useACK = true

[tcpout]
defaultGroup = idx_group
