[install]
is_configured = 1
state = enabled

[ui]
is_visible = 0
label = Indexer discovery

[launcher]
author = szilard
description = Configures  instances to connect to the central CLuster Manager with indexer discovery.
version = 1.0.0

[package]
id = szilard_enable_indexer_discovery